config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create]
  resources :organisations, only: [:index, :show, :new, :create, :edit, :update, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact #< ActiveRecord::Base
  include ActiveModel::Model
  attr_accessor :name, :email, :phone, :message
  validates :email, presence: true, format: {
    with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    message: "must be a valid email address"
  }
  validates :name, :message, presence: true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: :slugged

  belongs_to :user

  validates :name, presence: true

  # in case of 2 same name, the module will genrate a slug with Organisation ID.
  def slug_candidates
    random_number1 = rand(10)
    random_number2 = rand(10)
    random_number3 = rand(10)
    [
      :name,
      [:name, random_number1],
      [:name, random_number1, random_number2],
      [:name, random_number1, random_number2, random_number3]
    ]
  end

  # this will generate friendly urls
  # def to_param
  #   name.parameterize
  # end

  # to allow using "Organisation.find(params[:id])" in the contrleur,
  # even with friendy urls
  # def self.find(input)
  #   find_by_name(input)
  # end

  # better use a gem : https://github.com/norman/friendly_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :organisations, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit

  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end

  def after_sign_in_path_for(resource)
    organisations_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(message_params)
    if @contact.valid?
      mail = ContactMailer.general_message(@contact)
      mail.deliver_now
      flash[:notice] = "We have received your message and will be in touch soon!"
    else
      flash[:alert] = "There was an error sending your message. Please try again."
    end
    redirect_to root_path
  end

  private

  def message_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def index
    @organisations = current_user.organisations.order(:id)
    # @organisations = policy_scope(Organisation)
  end

  def show
    @organisation = Organisation.friendly.find(params[:id])

    @links = {}
    @links[:tripadvisor] = @organisation.tripadvisor_link if @organisation.tripadvisor_link.present?
    @links[:facebook] = convert_facebook_link(@organisation.facebook_link) if @organisation.facebook_link.present?
    @links[:google] = convert_google_link(@organisation.google_link) if @organisation.google_link.present?
    @links[:yelp] = @organisation.yelp_link if @organisation.yelp_link.present?

    render layout: 'organisation'
  end

  def new
    @organisation = Organisation.new
    # authorize @organisation
  end

  def create
    @organisation = Organisation.new(organisation_params)
    @organisation.user = current_user
    # authorize @organisation
    if @organisation.save
      redirect_to organisations_path
    else
      render :new
    end
  end

  def edit
    @organisation = Organisation.friendly.find(params[:id])
    raise unless @organisation.user == current_user
  end

  def update
    # @organisation = Organisation.find(params[:id])
    @organisation = current_user.organisations.friendly.find(params[:id])
    # authorize @organisation
    raise unless @organisation.user == current_user

    if @organisation.update(organisation_params)
      redirect_to organisations_path
    else
      render :edit
    end
  end

  def destroy
    @organisation = Organisation.friendly.find(params[:id])
    raise unless @organisation.user == current_user

    @organisation.destroy
    redirect_to organisations_path
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name, :presentation, :facebook_link, :tripadvisor_link, :google_link, :yelp_link)
  end

  def convert_google_link(g_link)
    return "https://search.google.com/local/writereview?placeid=" + g_link
  end

  def convert_facebook_link(bf_link)
    bf_link.gsub! ':', '%3A'
    bf_link.gsub! '/', '%2F'
    return "https://www.facebook.com/login/?next=" + bf_link
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @contact = Contact.new
    render layout: 'homepage'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
    <meta name="robots" content="index, follow">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>

      <%= javascript_pack_tag 'application' %>
    </div>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
    <meta name="robots" content="index, follow">
  </head>
  <body class="bg-white">
    <div class="container">
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>

      <%= javascript_pack_tag 'application' %>
    </div>
  </body>
</html>

app/views/layouts/organisation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
    <meta name="robots" content="noindex, nofollow">
    <% if @links.length == 1 %>
    <meta http-equiv="refresh" content="0.1; url=<%= @links.values[0] %>"/>
    <% end %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
    </div>
  </body>
</html>

app/views/organisations/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-12 col-md-6">
    <%= simple_form_for @organisation do |f| %>
      <% if @organisation.errors.any? %>
        <p class="text-danger"><%= @organisation.errors[:organisation].first  %></p>
      <% end %>
      <%= f.input :name, required: true, as: :string, label:"Name" %>
      <%= f.input :facebook_link, as: :string, label:"Facebook URL page" %>
      <%= f.input :google_link, as: :string, label:"Google Place ID" %>
      <%= f.input :yelp_link, as: :string, label:"Yelp URL page" %>
      <%= f.input :tripadvisor_link, as: :string, label:"Trip Advisor URL page" %>
      <%= f.button :submit, "Save", class: "btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organisations/index.html.erb
<h1 class="concert-title">All my organisations</h1>
<div class="index-organisations">
  <% @organisations.each do |organisation|%>
  <div class="qr-card">
    <div class="card-left">
      <h2> <%= organisation.name %></h2>
    </div>
    <div class="card-center">
      <% if organisation.facebook_link.present? %>
        <%= image_tag "facebook-avis.jpg" %>
      <%#= organisation.facebook_link %>
      <%#= link_to image_tag("image.png", :alt => "Image Description", :class => "css"), root_path %>
      <% end %>
      <% if organisation.tripadvisor_link.present? %>
        <%= image_tag "tripadvisor-avis.jpg" %>
      <% end %>
      <% if organisation.google_link.present? %>
        <%= image_tag "google-avis.jpg" %>
      <% end %>
      <% if organisation.yelp_link.present? %>
        <%= image_tag "yelp-avis.jpg" %>
      <% end %>
    </div>
    <div class="card-right">
      <%= link_to "Edit", edit_organisation_path(organisation) %><br>
      <%= link_to "View", organisation_path(organisation), class: "btn btn-primary", target: "_blank" %><br>
      <%= link_to "Delete", organisation_path(organisation),
      method: :delete,
      class: "text-danger",
      data: { confirm: "Are you sure?" } %>
    </div>
  </div>
  <% end %>
</div>
<div>
  <h2>New organisation ?</h2>
  <%= link_to "Create new one", new_organisation_path, class: "btn btn-primary"%>
</div>

app/views/organisations/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-12 col-md-6">
    <%= simple_form_for @organisation do |f| %>
      <% if @organisation.errors.any? %>
        <p class="text-danger"><%= @organisation.errors[:organisation].first  %></p>
      <% end %>
      <%= f.input :name, required: true, as: :string, label:"Name" %>
      <%= f.input :facebook_link, as: :string, label:"Facebook URL page" %>
      <%= f.input :google_link, as: :string, label:"Google Place ID" %>
      <%= f.input :yelp_link, as: :string, label:"Yelp URL page" %>
      <%= f.input :tripadvisor_link, as: :string, label:"Trip Advisor URL page" %>
      <%= f.button :submit, "Create new organisation", class: "btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organisations/show.html.erb
<% content_for :meta_title, "#{@organisation.name} - Let a review" %>
<% content_for :meta_description, "Easy way to let a review on social plateforms like Google, Facebook, Pinterest or Yelp for #{@organisation.name}" %>

<div class="qr-card text-center">
  <h1><%= @organisation.name %></h1>
  <% if @links.length == 0 %>
    <p> Sorry, no plateform available for now.</p>
  <% elsif @links.length == 1 %>
    <p>Just a second, you will be automatically redirected...<%= image_tag "loader.gif" %></p>
    <p>If nothing happen, <a href="/">please contact-us</a></p>
  <% else %>
    <p>Select your favorite plateform</p>
    <div class="d-flex flex-wrap justify-content-around">
      <% if @links.key?(:facebook) %>
        <%= link_to @links[:facebook] do %>
          <%= image_tag "facebook-avis.jpg" %>
        <% end %>
      <% end %>
      <% if @links.key?(:tripadvisor) %>
        <%= link_to @links[:tripadvisor] do %>
          <%= image_tag "tripadvisor-avis.jpg" %>
        <% end %>
      <% end %>
      <% if @links.key?(:google) %>
        <%= link_to @links[:google] do %>
          <%= image_tag "google-avis.jpg" %>
        <% end %>
      <% end %>
      <% if @links.key?(:yelp) %>
        <%= link_to @links[:yelp] do %>
          <%= image_tag "yelp-avis.jpg" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="text-center mt-1">
  Powered by <a href="/">Quality Reviews</a><%= image_tag "favicon/favicon-16x16.png" %>
</div>

app/views/pages/home.html.erb
<div class="homepage row mt-5 text-center justify-content-md-center">
  <div class="col-12 col-md-6">
    <%= image_tag "quality-reviews-logo.png" %>
    <h1>Feel free to contact us:</h1>
    <div class="mt-4">
      <%= render 'shared/contact' %>
    </div>
  </div>
</div>

app/views/shared/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157898046-1"></script>
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'UA-157898046-1');
</script>

app/views/shared/_contact.html.erb
<%= simple_form_for @contact do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, label: false, placeholder:"Name" %>
  <%= f.input :email, label: false, placeholder:"Email" %>
  <%= f.input :phone, as: :email, label: false, placeholder:"Phone" %>
  <%= f.input :message, as: :text, label: false, placeholder: "Your message" %>
  <%#= f.input :nickname, :hint => 'Leave this field blank!' %>
  <%= f.button :submit, "Contact us", class: "btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_head.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />
<!-- Icons -->
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_url('favicon/apple-touch-icon.png') %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_url('favicon/favicon-32x32.png') %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_url('favicon/favicon-16x16.png') %>">
<link rel="manifest" href="<%= image_url('favicon/site.webmanifest') %>">
<link rel="mask-icon" href="<%= image_url('favicon/safari-pinned-tab.svg') %>" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
<%= render 'shared/analytics' %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in?
    home_link = "/organisations"
  else
    home_link = "/"
  end %>
  <%= link_to home_link, class: "navbar-brand" do %>
    <%= image_tag "quality-reviews-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <!-- <li class="nav-item active"> -->
          <%#= link_to "Home", "#", class: "nav-link" %>
<!--         </li>-->
        <li class="nav-item">
          <%= link_to "My organisations", organisations_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <span class="dropdown-toggle nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My account</span>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My informations", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>